version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/student-management
      - JWT_SECRET=supersecretjwtkey_for_docker
      - NODE_ENV=development
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - mongo

  mongo:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
