import { Router } from 'express';
import * as attendanceController from '../controllers/attendanceController';
import { authenticate, authorize } from '../middlewares/auth';
import { Role } from '../models/User';
const router = Router();
router.use(authenticate);
router.post('/', authorize([Role.ADMIN]), attendanceController.markAttendance);
router.get('/student/:studentId', attendanceController.getStudentAttendance);
router.get('/report', authorize([Role.ADMIN]), attendanceController.getMonthlyReport);
export default router;
