import { Router } from 'express';
import * as courseController from '../controllers/courseController';
import { authenticate, authorize } from '../middlewares/auth';
import { Role } from '../models/User';
const router = Router();
router.use(authenticate);
router.get('/', courseController.getCourses);
router.post('/', authorize([Role.ADMIN]), courseController.createCourse);
router.post('/:id/enroll', authorize([Role.ADMIN]), courseController.enrollStudent);
router.get('/:id/students', authorize([Role.ADMIN]), courseController.getEnrolledStudents);
export default router;
