import { Router } from 'express';
import * as studentController from '../controllers/studentController';
import { authenticate, authorize } from '../middlewares/auth';
import { Role } from '../models/User';
import { upload } from '../middlewares/upload';
const router = Router();
router.use(authenticate);
router.get('/', studentController.getStudents);
router.get('/:id', studentController.getStudent);
router.put('/:id', authorize([Role.ADMIN]), studentController.updateStudent);
router.delete('/:id', authorize([Role.ADMIN]), studentController.deleteStudent);
router.post('/:id/upload', authorize([Role.ADMIN, Role.STUDENT]), upload.single('image'), studentController.uploadImage);
export default router;
